#########
#
# Variation on workshop-template-b, evanwill
# a Jekyll template for a simple workshop website
# https://github.com/evanwill/workshop-template-b
#
#########

#######
# SITE SETTINGS
#
# title appears in the header
title: Adobe PDF Accessibility Remediation Workshop
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon: 
# description, keywords, and image for meta tags
# these do not visibility appear on the pages, but used for SEO
description: "Guide for University of Idaho Faculty, Staff and Students."
keywords: 
# featured-image is added to metadata tags for social media sharing
# use a relative path to image in this repository or full URL
featured-image: "/images/banner.png"
# add search box to footer? true/false
search: true

# author settings for cc-by, appears in the footer and credits
author: Andrew Weymouth
# your github username for link [optional]
github_username: aweymo-ui
# year or date published
pub_year: 2025
# location of code, the full url to your github repository
source-code: https://github.com/aweymo-ui/remediate_pdfs

##########
# URL VARIABLES [optional!!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
# When using github pages just leave these blank!
#
# use url for the domain, e.g. https://evanwill.github.io
# on gh-pages follow the pattern: https://username.github.io
url: https://aweymo-ui.github.io/
# use baseurl to add subsection of the domain, e.g. /workshop-template-b
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl: /remediate_pdfs


##########
# GOOGLE ANALYTICS [optional!]
#
# leave this blank or comment out to NOT include google code
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
google-analytics-id: G-12NFKFDD58

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown

# THEME ICONS [optional!]
# default icons can be overridden or new icons can be added using "icons" object
# the template uses Bootstrap Icons, https://icons.getbootstrap.com/
# find the names on the BI icons page, e.g. file-image
#
# icons: 
#   icon-image: image
#   icon-audio: soundwave
#   icon-video: film
#   icon-pdf: file-pdf
#   icon-record: file-text
#   icon-panorama: image-alt
#   icon-compound-object: collection 
#   icon-multiple: postcard
#   icon-default: file-earmark # fall back icon
#   icon-back-to-top: arrow-up-square

